# Generated by Django 6.1 on 2026-09-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransfer',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
